services:

  Notification.controllers.SendWelcomeUserEmailController:
    class: ../../controllers/SendWelcomeUserEmailController
    arguments: ["@Shared.CommandBus"]

  Notification.controllers.StatusGetController:
    class: ../../controllers/StatusGetController
    arguments: []